# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

name: $(Date:yyyyMMdd)$(Rev:.rrr)-$(Build.SourceBranchName)

steps:
- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    dockerFile: AzureWebAppContainer/Dockerfile
    imageName: azwebappcontainer:$(Build.BuildNumber)
    useDefaultContext: false
    buildContext: .

- task: Docker@1
  displayName: Push image
  inputs:
    command: push
    azureSubscriptionEndpoint: ARMPre2015
    azureContainerRegistry: sparreio
    imageName: azwebappcontainer:$(Build.BuildNumber)