# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

name: $(Date:yyyyMMdd)$(Rev:.rrr)-$(Build.SourceBranchName)

steps:

- task: Bash@3
  displayName: Create version.txt file
  inputs:
    targetType: inline
    script: echo "$(Build.BuildNumber)" > version.txt

- task: Docker@1
  displayName: Build image
  inputs:
    command: build
    dockerFile: AzureWebAppContainer/Dockerfile
    imageName: sparreio.azurecr.io/azwebappcontainer:$(Build.BuildNumber)
    useDefaultContext: false
    buildContext: .

- task: Docker@1
  displayName: Push image
  inputs:
    command: push
    azureSubscriptionEndpoint: ARMPre2015
    azureContainerRegistry: sparreio.azurecr.io
    imageName: sparreio.azurecr.io/azwebappcontainer:$(Build.BuildNumber)